import type { Calendar, Lo, Student, WeekType } from "./lo";
import { Topic } from "./topic";
import type { IconNav, IconNavBar } from "../icons/icon-types";
export declare class Course {
    lo: Lo;
    topics: Topic[];
    units: Lo[];
    standardLos: Lo[];
    allLos: Lo[];
    url: string;
    authLevel: number;
    analytics: number;
    topicIndex: Map<string, Topic>;
    videos: Map<string, Lo>;
    talks: Map<string, Lo>;
    notes: Map<string, Lo>;
    labIndex: Map<string, Lo>;
    hydratedLabs: Map<string, any>;
    walls: Map<string, Lo[]>;
    calendar: Calendar;
    currentWeek: WeekType;
    companions: IconNavBar;
    wallBar: IconNavBar;
    profileBar: IconNavBar;
    constructor(url: string);
    fetchCourse(): Promise<void>;
    fetch(url: string, complete?: boolean): Promise<any>;
    populate(): void;
    addWall(type: string): void;
    showAllLos(): void;
    isPortfolio(): boolean;
    areVideosHidden(): boolean;
    areLabStepsAutoNumbered(): boolean;
    hasEnrollment(): boolean;
    hasWhiteList(): boolean;
    getStudents(): Student[];
    createCompanions(): void;
    createWallBar(): void;
    createWallLink(type: string): IconNav;
    initCalendar(): void;
}
